export const ADD_FILTER = "ADD_FILTER";
export const ADD_SORTBY = "ADD_SORTBY";
export const FILTERED_PRODUCTS = "FILTERED_PRPDUCTS";

export const productActions = {
  GET_PRODUCT_CATEGORIES: "GET_PRODUCT_CATEGORIES",
  SET_MODAL_STATE: "SET_MODAL_STATE",
  SET_LOADING_STATUS: "SET_LOADING_STATUS",
  GET_ALL_PRODUCTS: "GET_ALL_PRODUCTS",
  GET_PRODUCTS_BY_CATEGORY: "GET_PRODUCTS_BY_CATEGORY",
  RESET_PRODUCTS_FILTERS: "RESET_PRODUCTS_FILTERS",
  GET_SEARCHED_PRODUCTS: "GET_SEARCHED_PRODUCTS",
};

export const userActions = {
  SET_USER_LOGIN_STATUS: "SET_USER_LOGIN_STATUS",
  SET_USER_LOADING_STATUS: "SET_USER_LOADING_STATUS",
  UPDATE_USER_LOADING_STATUS: "UPDATE_USER_LOADING_STATUS",
  SET_USER_DETAILS: "SET_USER_DETAILS",
  GET_USER_DETAILS: "GET_USER_DETAILS",
  REGISTER_USER: "REGISTER_USER",
};

export const cartActions = {
  SET_CART: "SET_CART",
  GET_CART: "GET_CART",
  DELETE_FROM_CART: "DELETE_FROM_CART",
  EDIT_FROM_CART: "EDIT_FROM_CART",
  DELETE_ALL_FROM_CART: "DELETE_ALL_FROM_CART",
};
export const SET_LOADING_STATUS = "SET_LOADING_STATUS";
